# Site settings
title: sab's blog
description: >- # site description
  sab's blog
lang: en-US # default lang
timezone: US/Pacific # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: sab
  bio: >- # tell to the world
    i'm sab!
  email: raymondji@berkeley.edu # TODO: change email
  avatar: /assets/img/evanbot.png # change with your own avatar

# URL settings
url: "sab-blog.raymondji.com" # TODO: change site url
baseurl:
permalink: pretty
google_analytics: G-SP8B044YSR # should be unnecessary
fb_appid: # should be unneccessary

# jekyll/markdown setting, not necessary to change

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Homepage limit posts
number_of_posts: 100

# Build settings
remote_theme: cs161-staff/jekyll-klise@v1.2.1

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
